import { create } from "zustand";

export type Language = "ID" | "EN";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: "ID",
  setLanguage: (lang) => set({ language: lang }),
}));

export const translations = {
  ID: {
    // Topbar
    realtime: "REALTIME",
    connected: "TERHUBUNG",
    syncing: "SINKRONISASI",
    lastSync: "Terakhir sinkronisasi",
    ago: "detik lalu",
    aiHealthy: "AI SEHAT",
    aiOptimizing: "AI OPTIMALISASI",
    authorized: "Tersertifikasi",
    executiveAdmin: "Admin Eksekutif",
    searchCommands: "Cari perintah (⌘K)",
    language: "Bahasa",
    indonesian: "Bahasa Indonesia",
    english: "English",
    home: "Beranda",
    dashboardTitle: "Dashboard",
    productsTitle: "Produk",
    ordersTitle: "Pesanan",
    chatAiTitle: "Chat AI",
    customersTitle: "Pelanggan",
    settingsTitle: "Pengaturan",
    admin: "Admin",
    exchangeRateInfo: "Kurs Real-time",
    usdToIdr: "1 USD = Rp",
    exchangeRateAutoRefresh: "Kurs diperbarui otomatis setiap 30 menit menggunakan data publik terbaru.",

    // Inventory Page
    inventoryTitle: "Inventaris",
    inventorySubtitle: "Platform kecerdasan aset fashion tingkat perusahaan.",
    registerAsset: "Daftar Aset",
    activeSku: "Aset SKU Aktif",
    inventoryValue: "Nilai Inventaris",
    lowStockAlerts: "Peringatan Stok Rendah",
    alerts: "Peringatan",
    critical: "Kritis",
    searchPlaceholder: "Cari berdasarkan nama, SKU, atau brand...",
    noAssets: "Tidak ada aset yang ditemukan.",

    // Product Card
    msrpPrice: "Harga MSRP",
    baseSku: "SKU Dasar",
    globalStock: "Stok Global",
    units: "Unit",
    fabrication: "Fabrikasi",
    quality: "Kualitas",
    assetIntelligence: "Kecerdasan Aset",
    edit: "Ubah",
    duplicate: "Duplikat",
    archive: "Arsipkan",
    delete: "Hapus",

    // Modal
    registerAssetModal: "Daftar Aset",
    editAssetModal: "Ubah Aset",
    modalSubtitle: "Tentukan identitas fashion dan strategi komersial Anda.",
    assetImagery: "Citra Aset",
    selectCampaign: "Pilih Media Kampanye",
    assetName: "Nama Aset",
    assetSku: "SKU Aset",
    brand: "Merek",
    category: "Kategori",
    subcategory: "Subkategori",
    collection: "Seri / Koleksi",
    fabricationSilhouette: "Fabrikasi & Siluet",
    material: "Komposisi Material",
    gsm: "Berat Kain (GSM)",
    fitProfile: "Profil Fit",
    shoeFit: "Sistem Fit Sepatu",
    careLabel: "Label Perawatan",
    origin: "Negara Asal",
    commercialStrategy: "Strategi Komersial",
    basePrice: "Harga Dasar",
    discountPrice: "Harga Diskon",
    productionCost: "Biaya Produksi",
    estMargin: "Estimasi Margin Kotor",
    profitOptimized: "Profit Dioptimalkan",
    assetVisibility: "Visibilitas Aset",
    marketIntel: "Intel Pasar",
    demand: "Permintaan",
    bullish: "Meningkat",
    colorEngine: "Mesin Warna Tingkat Lanjut",
    defineVariants: "Tentukan varian dengan presisi.",
    pickColor: "Pilih Warna",
    hexCode: "Kode Hex",
    colorName: "Nama Warna",
    registerColor: "Daftar Warna",
    assetVariants: "Varian Aset",
    addVariant: "Tambah Varian Aset",
    sizeFit: "Ukuran / Fit",
    assignedColor: "Pilihan Warna",
    customSku: "SKU Kustom",
    optional: "Opsional",
    narrativeSeo: "Narasi Aset & SEO",
    urlSlug: "Slug URL",
    editorialNarrative: "Narasi Editorial",
    describeCraft: "Jelaskan keahlian dan filosofi desain...",
    discard: "Batal",
    saveDraft: "Simpan Draft",
    updateAsset: "Perbarui Aset",

    // Asset Intelligence
    velocity: "Kecepatan",
    sellThrough: "Penjualan",
    demandForecast: "Prediksi Permintaan",
    predictedSales: "Prediksi Penjualan",
    aiStrategy: "Strategi AI",
    recommendation: "Aset ini menunjukkan minat organik yang tinggi di kategori",
    stockAlloc: "Kami merekomendasikan peningkatan alokasi stok",
    upcomingSeason: "untuk musim mendatang.",

    // Dashboard
    aiStrategyBriefing: "Briefing Strategi AI",
    realtimeActive: "Realtime Aktif",
    operationalPacing: "Laju operasional adalah",
    vsForecast: "vs prediksi",
    intelligenceEngine: "Mesin intelijen telah mensintesis",
    criticalInterventions: "intervensi kritis",
    revenueMomentum: "Momentum pendapatan tetap kuat, namun",
    highVelocityDepletion: "SKU berkecepatan tinggi mendekati penipisan",
    forecastConfidence: "Keyakinan prediksi adalah",
    basedOnDemand: "berdasarkan lintasan permintaan saat ini",
    revenuePacing: "Laju Pendapatan",
    inventoryRisk: "Risiko Inventaris",
    nominal: "Nominal",
    actionQueue: "Antrean Tindakan",
    awaitingReview: "Menunggu Peninjauan",
    globalOpsStatus: "Status Ops Global",
    optimizing: "Mengoptimalkan",
    targetProgress: "Kemajuan Target Q2",
    totalRevenue: "Total Pendapatan",
    netIncome: "Pendapatan Bersih",
    totalOrders: "Total Pesanan",
    avgOrderValue: "Rata-rata Nilai Pesanan",
    criticalStock: "Stok Kritis",
    actions: "Tindakan",
    restockRequired: "Aksi restock diperlukan",
    predictiveRevenue: "Mesin Pendapatan Prediktif",
    aiMovingAverage: "Overlay rata-rata bergerak bertenaga AI dengan interval keyakinan 85%",
    forecastAccuracy: "Akurasi Prediksi",
    trendAcceleration: "Akselerasi Tren",
    actualRevenue: "Pendapatan Aktual",
    aiProjection: "Proyeksi AI",
    replenishmentForecast: "Prediksi Pengisian Stok Cerdas",
    demandForecasting: "Peramalan permintaan bertenaga AI untuk mengoptimalkan siklus pengisian inventaris (Unit/Pcs).",
    aiConfidence: "Keyakinan AI",
    runAiAnalysis: "Jalankan Analisis AI",
    actualDemand: "Permintaan Aktual",
    aiForecastedDemand: "Permintaan Diprediksi AI",
    productRating: "Rating Produk",
    impact: "Dampak",
    generation: "Generasi",
    flashSale: "Flash Sale",
    activeStrategy: "Strategi Aktif",
    holidayEvent: "Hari Libur/Acara",
    weekendForecast: "Prediksi Akhir Pekan",
    inventoryAlerts: "Peringatan Inventaris",
    aiReplenishmentMonitoring: "Pemantauan Pengisian Stok Bertenaga AI",
    criticalResponse: "Respon Kritis Diperlukan",
    viewAnalytics: "Lihat Analisis",
    currentStock: "Stok Saat Ini",
    aiThreshold: "Ambang Batas AI",
    depleting: "Habis / Menipis",
    reorder: "Pesan Ulang",
    profitMargin: "Analisis Margin Keuntungan",
    grossMarginProduct: "Margin kotor per produk utama",
    avgMargin: "Rata-rata Margin",
    bestItem: "Barang Terbaik",
    riskItem: "Barang Berisiko",
    revenueDistribution: "Distribusi Pendapatan",
    categoryBreakdown: "Breakdown per kategori produk",
    totalPeriodRevenue: "Total Pendapatan Periode",
    inventoryHealth: "Kesehatan Inventaris & Penipisan",
    aiVelocityDepletion: "Estimasi kehabisan stok berbasis AI velocity",
    safeStatus: "Semua inventaris dalam status aman.",
    healthScore: "Skor Kesehatan Keseluruhan",
    aiActionQueue: "Antrean Tindakan AI",
    autonomousWorkflow: "Deteksi anomali otonom & alur kerja mitigasi",
    forceSync: "Paksa Sinkronisasi",
    optimizeInventory: "Optimalkan Inventaris",
    affected: "Terdampak",
    estImpact: "Estimasi Dampak",
    activityStream: "Aliran Aktivitas Realtime",
    liveEvents: "Acara operasional langsung & log sistem",
    newOrderConfirmed: "Pesanan baru dikonfirmasi",
    demandSpike: "Lonjakan permintaan regional terdeteksi di",
    criticalStockWarning: "Peringatan Stok Kritis",
    viewAllActivity: "Lihat Semua Aktivitas",
    customerType: "Tipe Pelanggan",
    returningVsNew: "Analisis Pembeli Lama vs Baru",
    returning: "Lama",
    repeatRate: "Tingkat Pengulangan",
    conversionFunnel: "Intelijen Corong Konversi",
    customerJourney: "Analisis perjalanan pelanggan & drop-off",
    totalVisitors: "Total Pengunjung",
    productViews: "Tayangan Produk",
    addToCart: "Tambah ke Keranjang",
    checkout: "Checkout",
    successfulPayment: "Pembayaran Berhasil",
    overallCr: "CR Keseluruhan",
    cartAbandonment: "Pengabaian Keranjang",
    topRegions: "Wilayah Pembelian Teratas",
    revenueTerritory: "Distribusi pendapatan menurut wilayah",
    marketShare: "Estimasi Pangsa Pasar",
    geoExpansion: "Ekspansi Geografis",
    fullMapView: "Lihat Peta Lengkap",
    topProducts: "Produk Performa Teratas",
    basedOnVolume: "Berdasarkan volume penjualan unit",
    operationalProductivity: "Produktivitas Operasional",
    adminTasks: "Tugas admin & performa regional",
    priorityTasks: "Tugas Prioritas",
    trendingAboveAvg: "Trending di atas rata-rata P7",
    healthyMargin: "Margin operasional sehat",
    stagnantVsLastMonth: "Stagnan vs bulan lalu",
    restockActionRequired: "Aksi restock diperlukan",
    strong: "Kuat",
    elevated: "Meningkat",
    territoryDistribution: "Distribusi pendapatan per wilayah",
    estMarketShare: "Estimasi Pangsa Pasar",
    customerTypeAnalysis: "Analisis Pembeli Lama vs Baru",
    customerJourneyAnalysis: "Analisis perjalanan pelanggan & penurunan",
    avgClv: "Rata-rata CLV",
    salesIntensityHeatmap: "Peta Panas Intensitas Penjualan",
    transactionActivity: "Aktivitas transaksi per hari & jam",
    basedOnSalesVolume: "Berdasarkan volume penjualan unit",

    // Orders Page
    ordersSubtitle: "Kelola pesanan dan alur kerja logistik perusahaan.",
    orderId: "ID Pesanan",
    customer: "Pelanggan",
    date: "Tanggal",
    amount: "Jumlah",
    status: "Status",
    payment: "Pembayaran",
    fulfillment: "Pemenuhan",
    allOrders: "Semua Pesanan",
    pending: "Tertunda",
    processing: "Diproses",
    shipped: "Dikirim",
    delivered: "Diterima",
    cancelled: "Dibatalkan",
    viewDetails: "Lihat Detail",

    // Customers Page
    customersSubtitle: "Analisis profil dan perilaku pelanggan.",
    customerName: "Nama Pelanggan",
    email: "Email",
    location: "Lokasi",
    totalSpend: "Total Belanja",
    orderCount: "Jumlah Pesanan",
    lastOrder: "Pesanan Terakhir",
    customerSince: "Pelanggan Sejak",
    activeCustomers: "Pelanggan Aktif",
    newCustomers: "Pelanggan Baru",
    churnRisk: "Risiko Churn",

    // Chat AI Page
    chatAiSubtitle: "Asisten AI cerdas untuk analisis data fashion.",
    askAi: "Tanya AI sesuatu...",
    aiTyping: "AI sedang mengetik...",
    intelligenceMode: "Mode Intelijen",
    suggestedQueries: "Saran Pertanyaan",

    // Settings Page
    settingsTitleHeader: "Pengaturan Sistem",
    settingsSubtitle: "Kelola konfigurasi platform, kecerdasan AI, dan keamanan akun Anda.",
    adminProfile: "Profil Administrator",
    fullName: "Nama Lengkap",
    businessEmail: "Email Bisnis",
    operationalPreferences: "Preferensi Operasional",
    mainCurrency: "Mata Uang Utama",
    maintenanceMode: "Maintenance Mode",
    maintenanceDesc: "Nonaktifkan akses publik sementara untuk pemeliharaan sistem.",
    aiCoreConfig: "AI Core Configuration",
    replenishmentThreshold: "Replenishment Threshold",
    replenishmentDesc: "AI akan merekomendasikan restock saat inventaris mencapai ambang batas.",
    autonomousActions: "Autonomous Actions",
    autonomousDesc: "Izinkan AI mengotomatiskan rekomendasi alur kerja restock.",
    dynamicPricing: "Dynamic Pricing",
    dynamicPricingDesc: "Optimalkan harga produk berdasarkan permintaan dan tren penjualan.",
    predictiveAnalytics: "Predictive Analytics",
    predictiveDesc: "Prediksi tren fashion dan preferensi pelanggan berdasarkan data.",
    ageBasedRecommendation: "Rekomendasi Berbasis Usia",
    ageBasedDesc: "Gunakan analisis generasi pelanggan untuk rekomendasi produk.",
    recommendationLimit: "Batas Rekomendasi Produk",
    notificationChannels: "Saluran Notifikasi",
    emailDailyDigest: "Email Daily Digest",
    emailDigestDesc: "Terima ringkasan aktivitas harian melalui email.",
    pushNotifications: "Push Notifications",
    pushNotificationsDesc: "Notifikasi langsung ke browser atau aplikasi admin.",
    appearanceSettings: "Tampilan Antarmuka",
    appTheme: "Tema Aplikasi",
    lightMode: "Mode Terang",
    darkMode: "Mode Gelap",
    systemTheme: "Tema Sistem",
    languageSelection: "Pilihan Bahasa",
    securityPrivacy: "Keamanan & Privasi",
    changePassword: "Ubah Kata Sandi",
    changePasswordDesc: "Perbarui kredensial login Anda.",
    twoFactorAuth: "Autentikasi Dua Faktor",
    logoutAllDevices: "Logout All Devices",
    logoutAllDesc: "Keluar dari semua perangkat yang sedang login.",
    sessionTimeout: "Session Timeout",
    sessionTimeoutDesc: "Otomatis logout setelah periode tidak aktif.",
    autoBackup: "Auto Backup Data",
    autoBackupDesc: "Simpan snapshot basis data ke perangkat lokal secara berkala.",
    saveChanges: "Simpan Perubahan",
    discardChanges: "Batal",
    resetDefaults: "Reset ke Awal",
  },
  EN: {
    // Topbar
    realtime: "REALTIME",
    connected: "CONNECTED",
    syncing: "SYNCING",
    lastSync: "Last sync",
    ago: "s ago",
    aiHealthy: "AI HEALTHY",
    aiOptimizing: "AI OPTIMIZING",
    authorized: "Authorized",
    executiveAdmin: "Executive Admin",
    searchCommands: "Search commands (⌘K)",
    language: "Language",
    indonesian: "Indonesian",
    english: "English",
    home: "Home",
    dashboardTitle: "Dashboard",
    productsTitle: "Products",
    ordersTitle: "Orders",
    chatAiTitle: "Chat AI",
    customersTitle: "Customers",
    settingsTitle: "Settings",
    admin: "Admin",
    exchangeRateInfo: "Real-time Rate",
    usdToIdr: "1 USD = Rp",
    exchangeRateAutoRefresh: "The exchange rate should refresh automatically every 30 minutes using the latest available public exchange rate data.",

    // Inventory Page
    inventoryTitle: "Inventory",
    inventorySubtitle: "Enterprise-grade fashion asset intelligence platform.",
    registerAsset: "Register Asset",
    activeSku: "Active SKU Assets",
    inventoryValue: "Inventory Value",
    lowStockAlerts: "Low Stock Alerts",
    alerts: "Alerts",
    critical: "Critical",
    searchPlaceholder: "Search by name, SKU, or brand...",
    noAssets: "No assets detected.",

    // Product Card
    msrpPrice: "MSRP Price",
    baseSku: "Base SKU",
    globalStock: "Global Stock",
    units: "Units",
    fabrication: "Fabrication",
    quality: "Quality",
    assetIntelligence: "Asset Intelligence",
    edit: "Edit",
    duplicate: "Duplicate",
    archive: "Archive",
    delete: "Delete",

    // Modal
    registerAssetModal: "Register Asset",
    editAssetModal: "Edit Asset",
    modalSubtitle: "Define your fashion identity and commercial strategy.",
    assetImagery: "Asset Imagery",
    selectCampaign: "Select Campaign Media",
    assetName: "Asset Name",
    assetSku: "Asset SKU",
    brand: "Brand",
    category: "Category",
    subcategory: "Subcategory",
    collection: "Series / Collection",
    fabricationSilhouette: "Fabrication & Silhouette",
    material: "Material Composition",
    gsm: "Fabric Weight (GSM)",
    fitProfile: "Fit Profile",
    shoeFit: "Shoe Fit System",
    careLabel: "Care Label",
    origin: "Country of Origin",
    commercialStrategy: "Commercial Strategy",
    basePrice: "Base Price",
    discountPrice: "Discount Price",
    productionCost: "Production Cost",
    estMargin: "Est. Gross Margin",
    profitOptimized: "Profit Optimized",
    assetVisibility: "Asset Visibility",
    marketIntel: "Market Intel",
    demand: "Demand",
    bullish: "Bullish",
    colorEngine: "Advanced Color Engine",
    defineVariants: "Define variants with precision.",
    pickColor: "Pick Color",
    hexCode: "Hex Code",
    colorName: "Color Name",
    registerColor: "Register Color",
    assetVariants: "Asset Variants",
    addVariant: "Add Asset Variant",
    sizeFit: "Size / Fit",
    assignedColor: "Assigned Color Way",
    customSku: "Custom SKU",
    optional: "Optional",
    narrativeSeo: "Asset Narrative & SEO",
    urlSlug: "URL Slug",
    editorialNarrative: "Editorial Narrative",
    describeCraft: "Describe the craftsmanship and design philosophy...",
    discard: "Discard",
    saveDraft: "Save Draft",
    updateAsset: "Update Asset",

    // Asset Intelligence
    velocity: "Velocity",
    sellThrough: "Sell-Through",
    demandForecast: "Demand Forecast",
    predictedSales: "Predicted Sales",
    aiStrategy: "AI Strategy",
    recommendation: "This asset is showing high organic interest in the",
    stockAlloc: "category. We recommend increasing the",
    upcomingSeason: "stock allocations for the upcoming season.",

    // Dashboard
    aiStrategyBriefing: "AI Strategy Briefing",
    realtimeActive: "Realtime Active",
    operationalPacing: "Operational pacing is",
    vsForecast: "vs forecast",
    intelligenceEngine: "Intelligence engine has synthesized",
    criticalInterventions: "critical interventions",
    revenueMomentum: "Revenue momentum remains robust, however",
    highVelocityDepletion: "high-velocity SKUs are approaching depletion",
    forecastConfidence: "Forecast confidence is",
    basedOnDemand: "based on current demand trajectory",
    revenuePacing: "Revenue Pacing",
    inventoryRisk: "Inventory Risk",
    nominal: "Nominal",
    actionQueue: "Action Queue",
    awaitingReview: "Awaiting Review",
    globalOpsStatus: "Global Ops Status",
    optimizing: "Optimizing",
    targetProgress: "Q2 Target Progress",
    totalRevenue: "Total Revenue",
    netIncome: "Net Income",
    totalOrders: "Total Orders",
    avgOrderValue: "Avg Order Value",
    criticalStock: "Critical Stock",
    actions: "Actions",
    restockRequired: "Restock action required",
    predictiveRevenue: "Predictive Revenue Engine",
    aiMovingAverage: "AI-driven moving average overlay with 85% confidence intervals",
    forecastAccuracy: "Forecast Accuracy",
    trendAcceleration: "Trend Acceleration",
    actualRevenue: "Actual Revenue",
    aiProjection: "AI Projection",
    replenishmentForecast: "Smart Replenishment Forecast",
    demandForecasting: "AI-driven demand forecasting to optimize inventory replenishment cycles (Units/Pcs).",
    aiConfidence: "AI Confidence",
    runAiAnalysis: "Run AI Analysis",
    actualDemand: "Actual Demand",
    aiForecastedDemand: "AI Forecasted Demand",
    productRating: "Product Rating",
    impact: "Impact",
    generation: "Generation",
    flashSale: "Flash Sale",
    activeStrategy: "Active Strategy",
    holidayEvent: "Holiday/Event",
    weekendForecast: "Weekend Forecast",
    inventoryAlerts: "Inventory Alerts",
    aiReplenishmentMonitoring: "AI-Driven Replenishment Monitoring",
    criticalResponse: "Critical Response Needed",
    viewAnalytics: "View Analytics",
    currentStock: "Current Stock",
    aiThreshold: "AI Threshold",
    depleting: "Depleting",
    reorder: "Reorder",
    profitMargin: "Profit Margin Analysis",
    grossMarginProduct: "Gross margin per main product",
    avgMargin: "Avg Margin",
    bestItem: "Best Item",
    riskItem: "Risk Item",
    revenueDistribution: "Revenue Distribution",
    categoryBreakdown: "Breakdown per product category",
    totalPeriodRevenue: "Total Period Revenue",
    inventoryHealth: "Inventory Health & Depletion",
    aiVelocityDepletion: "AI velocity-based depletion estimation",
    safeStatus: "All inventory in safe status.",
    healthScore: "Overall Health Score",
    aiActionQueue: "AI Action Queue",
    autonomousWorkflow: "Autonomous anomaly detection & mitigation workflows",
    forceSync: "Force Sync",
    optimizeInventory: "Optimize Inventory",
    affected: "Affected",
    estImpact: "Est. Impact",
    activityStream: "Realtime Activity Stream",
    liveEvents: "Live operational events & system logs",
    newOrderConfirmed: "New order confirmed",
    demandSpike: "Regional demand spike detected in",
    criticalStockWarning: "Critical Stock Warning",
    viewAllActivity: "View All Activity",
    customerType: "Customer Type",
    returningVsNew: "Returning vs New Buyers Analysis",
    returning: "Returning",
    repeatRate: "Repeat Rate",
    conversionFunnel: "Conversion Funnel Intelligence",
    customerJourney: "Customer journey & drop-off analysis",
    totalVisitors: "Total Visitors",
    productViews: "Product Views",
    addToCart: "Add to Cart",
    checkout: "Checkout",
    successfulPayment: "Successful Payment",
    overallCr: "Overall CR",
    cartAbandonment: "Cart Abandonment",
    topRegions: "Top Buying Regions",
    revenueTerritory: "Revenue distribution by territory",
    marketShare: "Est. Market Share",
    geoExpansion: "Geographic Expansion",
    fullMapView: "Full Map View",
    topProducts: "Top Performing Products",
    basedOnVolume: "Based on unit sales volume",
    operationalProductivity: "Operational Productivity",
    adminTasks: "Admin tasks & regional performance",
    priorityTasks: "Priority Tasks",
    trendingAboveAvg: "Trending above P7 average",
    healthyMargin: "Healthy operational margin",
    stagnantVsLastMonth: "Stagnant vs last month",
    restockActionRequired: "Restock action required",
    strong: "Strong",
    elevated: "Elevated",
    territoryDistribution: "Revenue distribution by territory",
    estMarketShare: "Est. Market Share",
    customerTypeAnalysis: "Returning vs New Buyers Analysis",
    customerJourneyAnalysis: "Customer journey & drop-off analysis",
    avgClv: "Avg. CLV",
    salesIntensityHeatmap: "Sales Intensity Heatmap",
    transactionActivity: "Transaction activity by day & hour",
    basedOnSalesVolume: "Based on unit sales volume",

    // Orders Page
    ordersSubtitle: "Manage orders and enterprise logistics workflows.",
    orderId: "Order ID",
    customer: "Customer",
    date: "Date",
    amount: "Amount",
    status: "Status",
    payment: "Payment",
    fulfillment: "Fulfillment",
    allOrders: "All Orders",
    pending: "Pending",
    processing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    viewDetails: "View Details",

    // Customers Page
    customersSubtitle: "Analyze customer profiles and behavior.",
    customerName: "Customer Name",
    email: "Email",
    location: "Location",
    totalSpend: "Total Spend",
    orderCount: "Order Count",
    lastOrder: "Last Order",
    customerSince: "Customer Since",
    activeCustomers: "Active Customers",
    newCustomers: "New Customers",
    churnRisk: "Churn Risk",

    // Chat AI Page
    chatAiSubtitle: "Intelligent AI assistant for fashion data analysis.",
    askAi: "Ask AI something...",
    aiTyping: "AI is typing...",
    intelligenceMode: "Intelligence Mode",
    suggestedQueries: "Suggested Queries",

    // Settings Page
    settingsTitleHeader: "System Settings",
    settingsSubtitle: "Manage platform configurations, AI intelligence, and account security.",
    adminProfile: "Administrator Profile",
    fullName: "Full Name",
    businessEmail: "Business Email",
    operationalPreferences: "Operational Preferences",
    mainCurrency: "Main Currency",
    maintenanceMode: "Maintenance Mode",
    maintenanceDesc: "Temporarily disable public access for system maintenance.",
    aiCoreConfig: "AI Core Configuration",
    replenishmentThreshold: "Replenishment Threshold",
    replenishmentDesc: "AI will recommend restocking when inventory reaches the threshold.",
    autonomousActions: "Autonomous Actions",
    autonomousDesc: "Allow AI to automate restock workflow recommendations.",
    dynamicPricing: "Dynamic Pricing",
    dynamicPricingDesc: "Optimize product pricing based on demand and sales trends.",
    predictiveAnalytics: "Predictive Analytics",
    predictiveDesc: "Predict fashion trends and customer preferences based on data.",
    ageBasedRecommendation: "Age-Based Recommendation",
    ageBasedDesc: "Use customer generation analysis for product recommendations.",
    recommendationLimit: "Product Recommendation Limit",
    notificationChannels: "Notification Channels",
    emailDailyDigest: "Email Daily Digest",
    emailDigestDesc: "Receive a daily activity summary via email.",
    pushNotifications: "Push Notifications",
    pushNotificationsDesc: "Direct notifications to your browser or admin app.",
    appearanceSettings: "Interface Appearance",
    appTheme: "Application Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemTheme: "System Theme",
    languageSelection: "Language Selection",
    securityPrivacy: "Security & Privacy",
    changePassword: "Change Password",
    changePasswordDesc: "Update your login credentials.",
    twoFactorAuth: "Two-Factor Authentication",
    logoutAllDevices: "Logout All Devices",
    logoutAllDesc: "Sign out of all devices currently logged in.",
    sessionTimeout: "Session Timeout",
    sessionTimeoutDesc: "Automatically log out after an inactive period.",
    autoBackup: "Auto Backup Data",
    autoBackupDesc: "Save database snapshots to your local device periodically.",
    saveChanges: "Save Changes",
    discardChanges: "Discard",
    resetDefaults: "Reset Defaults",
  }
};
